import type { PromptRegistryEntry } from "./promptTypes";

const model = process.env.OPENAI_MODEL_TEXT || process.env.OPENAI_MODEL || "gpt-5.1";

const json = "json" as const;

export const promptRegistry: PromptRegistryEntry[] = [
  {
    key: "daily-content-pack",
    filename: "social/daily-content-pack.md",
    title: "Daily Content Pack Generator",
    description: "Generates a review-ready daily pack across selected brands and platforms.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["date", "dailyTheme", "selectedBrands", "selectedPlatforms", "brandContext", "platformContext"],
    optionalVariables: ["strategicPriority", "activeCampaigns", "currentOffers", "recentPerformanceContext", "businessNotes"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "brand-selection",
    filename: "social/brand-selection.md",
    title: "Daily Brand Selection",
    description: "Chooses which umbrella brands should post for a daily theme.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["date", "dailyTheme", "brandContext"],
    optionalVariables: ["businessPriorities", "activeCampaigns", "recentPerformanceContext", "postingFrequencyRules"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "platform-post",
    filename: "social/platform-post.md",
    title: "Platform-Native Post",
    description: "Writes one native social post for a brand, platform, pillar, campaign, and audience.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["brand", "platform", "contentPillar", "audience", "dailyTheme", "voiceGuidelines"],
    optionalVariables: ["campaign", "offer", "postObjective", "hookDirection", "recentPerformanceContext", "forbiddenPhrases", "ctaOptions"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "image-prompt",
    filename: "social/image-prompt.md",
    title: "Image Prompt",
    description: "Creates image prompt, design notes, alt text, and filename direction.",
    category: "image",
    version: "1.0.0",
    requiredVariables: ["brand", "platform", "post", "visualStyle"],
    optionalVariables: ["contentPillar", "campaign", "imageStyleRules", "forbiddenVisualElements", "assetFilenameFormat"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "carousel-outline",
    filename: "social/carousel-outline.md",
    title: "Carousel Outline",
    description: "Generates a 5-8 slide Instagram or LinkedIn carousel outline.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["brand", "platform", "dailyTheme", "contentPillar", "audience"],
    optionalVariables: ["postObjective", "offer", "voiceGuidelines", "visualStyle"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "short-video-script",
    filename: "social/short-video-script.md",
    title: "Short Video Script",
    description: "Generates a short-form video script and shot list.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["brand", "platform", "dailyTheme", "contentPillar", "audience"],
    optionalVariables: ["postObjective", "offer", "voiceGuidelines", "visualContext"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "reddit-discussion",
    filename: "social/reddit-discussion.md",
    title: "Reddit Discussion",
    description: "Creates a non-promotional Reddit discussion post.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["brand", "dailyTheme", "audience", "communityType", "contentPillar"],
    optionalVariables: ["relevantExperience", "disclosureRequirement"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "google-business-profile-post",
    filename: "social/google-business-profile-post.md",
    title: "Google Business Profile Post",
    description: "Creates local service-oriented Google Business Profile updates.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["brand", "serviceArea", "service", "dailyTheme", "cta"],
    optionalVariables: ["offer", "postObjective", "proofPoint"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "newsletter-blurb",
    filename: "social/newsletter-blurb.md",
    title: "Newsletter Blurb",
    description: "Turns source social content into a useful newsletter section.",
    category: "repurposing",
    version: "1.0.0",
    requiredVariables: ["brand", "dailyTheme", "sourcePosts", "audience"],
    optionalVariables: ["offer", "cta"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "caption-rewrite",
    filename: "social/caption-rewrite.md",
    title: "Caption Rewrite",
    description: "Rewrites weak captions while preserving truth and brand voice.",
    category: "approval",
    version: "1.0.0",
    requiredVariables: ["originalCaption", "brand", "platform", "rewriteReason", "voiceGuidelines"],
    optionalVariables: ["desiredDirection", "forbiddenPhrases", "ctaOptions"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "approval-summary",
    filename: "social/approval-summary.md",
    title: "Approval Summary",
    description: "Summarizes generated content for quick human review.",
    category: "approval",
    version: "1.0.0",
    requiredVariables: ["contentPack", "posts", "imagePrompts", "brandContext"],
    optionalVariables: ["knownRisks"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "weekly-research-brief",
    filename: "social/weekly-research-brief.md",
    title: "Weekly Research Brief",
    description: "Creates a weekly content intelligence brief for the umbrella.",
    category: "research",
    version: "1.0.0",
    requiredVariables: ["weekStart", "weekEnd", "brandContext"],
    optionalVariables: ["currentOffers", "activeCampaigns", "recentPerformanceContext", "audienceNotes", "marketNotes"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "dashboard-analysis",
    filename: "social/dashboard-analysis.md",
    title: "Social Dashboard Analysis",
    description: "Analyzes sanitized dashboard data and produces practical recommendations.",
    category: "analytics",
    version: "1.0.0",
    requiredVariables: ["dateRange", "sanitizedMetricsSummary", "topPosts", "weakPosts"],
    optionalVariables: ["brand", "platform", "benchmarks", "activeCampaigns"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "sanitized_metrics_only",
    parseStrategy: json,
  },
  {
    key: "metrics-insight-summary",
    filename: "social/metrics-insight-summary.md",
    title: "Metrics Insight Summary",
    description: "Converts rollups and insights into saved recommendation records.",
    category: "analytics",
    version: "1.0.0",
    requiredVariables: ["metricRollups", "performanceInsights", "dateRange"],
    optionalVariables: ["brand", "platform"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "sanitized_metrics_only",
    parseStrategy: json,
  },
  {
    key: "performance-context-for-generation",
    filename: "social/performance-context-for-generation.md",
    title: "Performance Context For Generation",
    description: "Creates compact sanitized guidance for future content prompts.",
    category: "analytics",
    version: "1.0.0",
    requiredVariables: ["brand", "dateRange", "topPerformancePatterns", "weakPerformancePatterns"],
    optionalVariables: ["platform", "acceptedInsights", "contentGaps"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "sanitized_metrics_only",
    parseStrategy: json,
  },
  {
    key: "repurpose-plan",
    filename: "social/repurpose-plan.md",
    title: "Repurpose Plan",
    description: "Creates platform-native repurposing plans from a strong source item.",
    category: "repurposing",
    version: "1.0.0",
    requiredVariables: ["sourceItem", "brand", "originalPlatform", "targetPlatforms", "reason"],
    optionalVariables: ["recentPerformanceContext"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "campaign-plan",
    filename: "social/campaign-plan.md",
    title: "Campaign Plan",
    description: "Creates a campaign plan for a brand, offer, and date range.",
    category: "campaign",
    version: "1.0.0",
    requiredVariables: ["brand", "offer", "campaignGoal", "startDate", "endDate", "audience", "platforms"],
    optionalVariables: ["constraints", "recentPerformanceContext"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "site-audit-to-content",
    filename: "social/site-audit-to-content.md",
    title: "Site Audit To Content",
    description: "Turns sanitized audit findings into public-safe educational content.",
    category: "generation",
    version: "1.0.0",
    requiredVariables: ["brand", "auditSource", "websiteUrl", "auditFindings", "audience", "platform"],
    optionalVariables: ["offer"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "raw_private_data_blocked",
    parseStrategy: json,
  },
  {
    key: "monthly-content-map",
    filename: "social/monthly-content-map.md",
    title: "Monthly Content Map",
    description: "Creates a balanced monthly map for the umbrella.",
    category: "campaign",
    version: "1.0.0",
    requiredVariables: ["month", "brands", "campaigns", "offers", "businessPriorities"],
    optionalVariables: ["postingFrequencyRules", "recentPerformanceContext", "knownDates"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
  {
    key: "prompt-quality-check",
    filename: "social/prompt-quality-check.md",
    title: "Prompt Output Quality Check",
    description: "Reviews generated output for brand fit, usefulness, privacy, and quality.",
    category: "quality-control",
    version: "1.0.0",
    requiredVariables: ["generatedOutput", "brandContext", "platformContext", "promptKey"],
    optionalVariables: ["knownRisks"],
    outputMode: json,
    recommendedModel: model,
    privacyLevel: "private_business_context",
    parseStrategy: json,
  },
];

export function getPromptMetadata(promptKey: string) {
  const metadata = promptRegistry.find((entry) => entry.key === promptKey);
  if (!metadata) throw new Error(`Unknown prompt key: ${promptKey}`);
  return metadata;
}

export const promptKeys = promptRegistry.map((entry) => entry.key);
